version: v0.13.0

dsn: postgres://mainflux:mainflux@kratos-postgres:5432/users

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:4455/
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: mainflux
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true
    oidc:
      config:
        providers:
          - id: google
            provider: google
            client_id: <GOOGLE_CLIENT_ID>
            client_secret: <GOOGLE_CLIENT_SECRET>
            issuer_url: https://accounts.google.com # Replace this with the providers issuer URL
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogICAgZW1haWxfdmVyaWZpZWQ6IHRydWUsCiAgfSArIHN0ZC5leHRWYXIoJ2NsYWltcycpOwogIAogIHsKICAgIGlkZW50aXR5OiB7CiAgICAgIHRyYWl0czogewogICAgICAgIFtpZiAnZW1haWwnIGluIGNsYWltcyAmJiBjbGFpbXMuZW1haWxfdmVyaWZpZWQgdGhlbiAnZW1haWwnIGVsc2UgbnVsbF06IGNsYWltcy5lbWFpbCwKICAgICAgICB1c2VybmFtZTogY2xhaW1zLm5hbWUsCiAgICAgICAgbmV3c2xldHRlcjogdHJ1ZSwKICAgICAgICBbaWYgJ2hkJyBpbiBjbGFpbXMgJiYgY2xhaW1zLmVtYWlsX3ZlcmlmaWVkIHRoZW4gJ2hkJyBlbHNlIG51bGxdOiBjbGFpbXMuaGQsCiAgICAgIH0sCiAgICB9LAogIH0="
            scope:
              - email
              - profile
          - id: github
            provider: github
            client_id: <GITHUB_CLIENT_ID>
            client_secret: <GITHUB_CLIENT_SECRET>
            mapper_url: "base64://bG9jYWwgY2xhaW1zID0gewogICAgZW1haWxfdmVyaWZpZWQ6IHRydWUsCn0gKyBzdGQuZXh0VmFyKCdjbGFpbXMnKTsKICAKewogICAgaWRlbnRpdHk6IHsKICAgICAgICB0cmFpdHM6IHsKICAgICAgICAgICAgW2lmICdlbWFpbCcgaW4gY2xhaW1zICYmIGNsYWltcy5lbWFpbF92ZXJpZmllZCB0aGVuICdlbWFpbCcgZWxzZSBudWxsXTogY2xhaW1zLmVtYWlsLAogICAgICAgICAgICB1c2VybmFtZTogY2xhaW1zLm5hbWUsCiAgICAgICAgICAgIG5ld3NsZXR0ZXI6IHRydWUsCiAgICAgICAgICAgIFtpZiAnaGQnIGluIGNsYWltcyAmJiBjbGFpbXMuZW1haWxfdmVyaWZpZWQgdGhlbiAnaGQnIGVsc2UgbnVsbF06IGNsYWltcy5oZCwKICAgICAgICB9LAogICAgfSwKfQ=="
            scope:
              - user:email
              - read:user

      enabled: true
  flows:
    error:
      ui_url: http://127.0.0.1:4455/error

    settings:
      ui_url: http://127.0.0.1:4455/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4455/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4455/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:4455/

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:4455/login

    login:
      ui_url: http://127.0.0.1:4455/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:4455/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - McBNO88UQxixLvMqRbuLd8XBzFdnIZzisPXQHbA52GNp3dM6kbt6I4pzylmKXlgmHKr56P8rpugDyDanbnyuSJVCLsi3FLvLYTQA2QPXcVMFpSSXrtmbwKumRyuesgxA
  cipher:
    - d8HflHOLXeKXkn8siJdVSBUSGhACTQ28

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 10

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
